In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [23]:
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, Ridge
from sklearn.svm import SVR
from sklearn.svm import LinearSVR
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error

from sklearn.model_selection import GridSearchCV

In [3]:
pwd

'C:\\Users\\Luli\\Desktop\\UTN\\phyton\\Clase 07\\clusterai_2020-master\\clases\\clase_07'

In [4]:
ls

 El volumen de la unidad C no tiene etiqueta.
 El número de serie del volumen es: 7015-57B3

 Directorio de C:\Users\Luli\Desktop\UTN\phyton\Clase 07\clusterai_2020-master\clases\clase_07

16/10/2020  06:07 p. m.    <DIR>          .
16/10/2020  06:07 p. m.    <DIR>          ..
16/10/2020  03:03 p. m.    <DIR>          .ipynb_checkpoints
10/10/2020  08:52 a. m.             2.408 clusterai_2020_clase07_clustering_asignacion_properati.ipynb
16/10/2020  05:14 p. m.           318.736 clusterai_2020_clase07_clustering_credit.ipynb
16/10/2020  04:41 p. m.           392.533 clusterai_2020_clase07_clustering_vinos.ipynb
10/10/2020  08:52 a. m.         1.537.377 clusterai_2020_clase07_presentacion.pdf
16/10/2020  06:07 p. m.            11.107 ML_Strategy_Vigon.ipynb
14/10/2020  03:45 p. m.               367 X_test.csv
14/10/2020  03:45 p. m.             3.662 Xy_train.csv
               7 archivos      2.266.190 bytes
               3 dirs  373.229.813.760 bytes libres


In [13]:
Xy_train=pd.read_csv(r'C:\Users\Luli\Desktop\UTN\phyton\Clase 07\clusterai_2020-master\clases\clase_07\Xy_train.csv')
X_test=pd.read_csv(r'C:\Users\Luli\Desktop\UTN\phyton\Clase 07\clusterai_2020-master\clases\clase_07\X_test.csv')

In [14]:
xtrain = Xy_train.iloc[:,:-1].values
ytrain = Xy_train.iloc[:,1].values
print(xtrain.shape,ytrain.shape)

(100, 1) (100,)


In [15]:
#auto scaling train set y test set
scaler = preprocessing.StandardScaler().fit(xtrain)
xtrain_scal = scaler.transform(xtrain) 
xtest_scal = scaler.transform(X_test)

# Linear Regression

In [17]:
#Definimos el estimador
estLR = LinearRegression()

In [18]:
#Definimos diccionario con hyperparametros
parameters = {'fit_intercept' : [False, True]}

In [19]:
#Definimos la cantidad de folds para validar
n_folds = 5
#Definimos el objeto grid search con los parametros anteriores
gs = GridSearchCV(estLR, param_grid=parameters, cv=n_folds, refit=True, scoring="neg_mean_squared_error")
gs.fit(xtrain_scal, ytrain)

GridSearchCV(cv=5, error_score=nan,
             estimator=LinearRegression(copy_X=True, fit_intercept=True,
                                        n_jobs=None, normalize=False),
             iid='deprecated', n_jobs=None,
             param_grid={'fit_intercept': [False, True]},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring='neg_mean_squared_error', verbose=0)

In [20]:
print(gs.best_estimator_, "\n")
print(gs.best_params_, "\n")
print(gs.best_score_, "\n")

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False) 

{'fit_intercept': True} 

-3.6488432812686495 



In [21]:
# Predicciones
ypred = gs.best_estimator_.predict(xtest_scal)
ypred

array([5.96759494, 6.03934112, 7.34459198, 3.89326209, 4.07392204,
       6.17817658, 7.23702974, 2.6544078 , 7.5808747 , 4.05645739,
       4.3667152 , 6.10182228, 7.60127901, 2.95434962, 5.15379446,
       7.02760273, 5.30666086, 5.88178477, 6.50265793, 6.02722072])

# Ridge Regression

In [24]:
# Ahora cambiamos el estimador, usaremos Ridge Regression
estRR = Ridge()
# Lista del parametro lambda (llamado 'alpha' en el GridSearch )
lambdas = [-1.4,-1.38,-1.35,-1.32,-1.3,-1.28,-1.25]

In [25]:
# Juntamos el diccionario de parametros
parameters = {'alpha': lambdas}

In [26]:
# Definimos nuevamente el objeto GS con los parametros previamente definidos
gs2 = GridSearchCV(estRR, param_grid=parameters,refit=True, cv=n_folds, scoring="neg_mean_squared_error")


In [27]:
# Entrenamos
gs2.fit(xtrain_scal, ytrain)

GridSearchCV(cv=5, error_score=nan,
             estimator=Ridge(alpha=1.0, copy_X=True, fit_intercept=True,
                             max_iter=None, normalize=False, random_state=None,
                             solver='auto', tol=0.001),
             iid='deprecated', n_jobs=None,
             param_grid={'alpha': [-1.4, -1.38, -1.35, -1.32, -1.3, -1.28,
                                   -1.25]},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring='neg_mean_squared_error', verbose=0)

In [28]:
# Mostramos el mejor estimador, sus hyperparametros seleccionados y su resultado
print(gs2.best_estimator_, "\n")
print(gs2.best_params_, "\n")
print(gs2.best_score_, "\n")

Ridge(alpha=-1.3, copy_X=True, fit_intercept=True, max_iter=None,
      normalize=False, random_state=None, solver='auto', tol=0.001) 

{'alpha': -1.3} 

-3.6482535486442083 



In [43]:
#Predicciones
ypred2 = gs2.best_estimator_.predict(xtest_scal)
ypred2

array([5.97937724, 6.0520684 , 7.37451101, 3.87772288, 4.06076234,
       6.19273249, 7.26553205, 2.62255136, 7.61390586, 4.04306766,
       4.35741194, 6.11537251, 7.63457893, 2.92644378, 5.154858  ,
       7.05334662, 5.30973784, 5.89243684, 6.52148766, 6.03978836])

# SVR

In [30]:
# Estimador
estSVR = SVR(max_iter=25000)
# Lista del parametro lambda (parametro 'alpha')
parameters = {'C' : [1000,1500,2000,3000,5000],
              'epsilon' : [0.001, 0.01, 0.1,1, 10,100],
             'gamma':[0.001, 0.01, 0.1,1, 10,100]}
# Definimos nuevamente el objeto GS con los parametros previamente definidos
gs3 = GridSearchCV(estSVR, param_grid=parameters,refit=True,
                  cv=n_folds, scoring="neg_mean_squared_error",
                  verbose=3, n_jobs=3)

In [31]:
# Entrenamos
gs3.fit(xtrain_scal, ytrain)
print(gs3.best_estimator_, "\n")
print(gs3.best_params_, "\n")
print(gs3.best_score_, "\n")
# Prediccion + Metricas
svr_prediction = gs3.best_estimator_.predict(xtest_scal)

Fitting 5 folds for each of 180 candidates, totalling 900 fits


[Parallel(n_jobs=3)]: Using backend LokyBackend with 3 concurrent workers.
[Parallel(n_jobs=3)]: Done  26 tasks      | elapsed:   10.8s
[Parallel(n_jobs=3)]: Done 530 tasks      | elapsed:   21.8s


SVR(C=1500, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma=1,
    kernel='rbf', max_iter=25000, shrinking=True, tol=0.001, verbose=False) 

{'C': 1500, 'epsilon': 0.1, 'gamma': 1} 

-0.6161412021487849 



[Parallel(n_jobs=3)]: Done 900 out of 900 | elapsed:   33.7s finished


In [42]:
#Predicciones
ypred3 = gs.best_estimator_.predict(xtest_scal)
ypred3

array([5.96759494, 6.03934112, 7.34459198, 3.89326209, 4.07392204,
       6.17817658, 7.23702974, 2.6544078 , 7.5808747 , 4.05645739,
       4.3667152 , 6.10182228, 7.60127901, 2.95434962, 5.15379446,
       7.02760273, 5.30666086, 5.88178477, 6.50265793, 6.02722072])

# KNN

In [33]:
from sklearn.neighbors import KNeighborsRegressor
from sklearn import neighbors
parameters_k = np.arange(0,20,1)

In [34]:
parameters_knn = [{'n_neighbors': parameters_k}]

In [35]:
for i, weights in enumerate(['uniform', 'distance']):
    knn = neighbors.KNeighborsRegressor(n_neighbors=5, weights=weights)

In [37]:
gs4 = GridSearchCV(knn, param_grid=parameters_knn,refit=True,
                  cv=n_folds, scoring="neg_mean_squared_error",
                  verbose=3, n_jobs=3)

In [39]:
# Entrenamos
gs4.fit(xtrain_scal, ytrain)
print(gs4.best_estimator_, "\n")
print(gs4.best_params_, "\n")
print(gs4.best_score_, "\n")

Fitting 5 folds for each of 20 candidates, totalling 100 fits


[Parallel(n_jobs=3)]: Using backend LokyBackend with 3 concurrent workers.


KNeighborsRegressor(algorithm='auto', leaf_size=30, metric='minkowski',
                    metric_params=None, n_jobs=None, n_neighbors=8, p=2,
                    weights='distance') 

{'n_neighbors': 8} 

-0.950113783374178 



[Parallel(n_jobs=3)]: Done  27 tasks      | elapsed:    6.2s
[Parallel(n_jobs=3)]: Done 100 out of 100 | elapsed:    6.4s finished


In [44]:
# Prediccion
svr_prediction = gs4.best_estimator_.predict(xtest_scal)
svr_prediction

array([ 2.92393505,  3.26962092,  7.46609246,  5.3709889 ,  4.97771795,
        3.72960515,  7.17188444,  1.06742847,  9.89531366,  5.1210491 ,
        5.46862087,  3.53654039, 10.10370806,  2.14385093,  4.09004793,
        6.33895138,  5.00254869,  2.94088323,  4.14479879,  3.21830652])